accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('signup/', views.UserSignUpView.as_view(), name='signup'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
	path('', views.IndexView.as_view(), name='index')
]

sub4sub/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.returnToHome),

    path('home/', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('survey/', include('survey.urls')),
    path('dashboard/', include('dashboard.urls')),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import generic

class IndexView(generic.TemplateView):
	template_name = 'home/index.html'

home/templates/home/index.html
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Home | SubForSub - The Best SubForSub System for You To Get More Subscribers</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% load static %}
    <!-- SEO METAS LISTOUT -->
    {% include 'seo_metas.html' %}
    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/slick.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/slicknav.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
</head>

<body>
    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <div class="col-xl-3 col-lg-2">
                            <div class="logo">
                                <a href="{% url 'home:index' %}">
                                    <h3 class="logo-h3">SubForSub</h3>
                                </a>
                            </div>
                        </div>
                        <div class="col-xl-6 col-lg-7">
                            <div class="main-menu  d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
                                        <li><a class="active" href="{% url 'home:index' %}">Home</a></li>
                                        <li><a href="{% url 'accounts:signup' %}">Get Started Now</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                            <div class="Appointment">
                                <div class="book_btn d-none d-lg-block">
                                    <a href="{% url 'accounts:login' %}">Login</a>
                                </div>
                            </div>
                        </div>
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    <!-- slider_area_start -->
    <div class="slider_area">
        <div class="single_slider  d-flex align-items-center slider_bg_1">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-xl-7 col-md-6">
                        <div class="slider_text ">
                            <h3 class="wow fadeInDown" data-wow-duration="1s" data-wow-delay=".1s" >Best Sub For Sub System<br>
                                All in One</h3>
                            <p class="wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".1s">Subscribe to other channels and also get subscribed super fast! You'll get instant subscribers within 20 minutes after You signup. Our platform has lots of other methods also for getting subscribers fast. They are the sub4sub method, instant subscriber method, and survey completing method. So are you ready to boost Your channel?</p>
                            <div class="video_service_btn wow fadeInLeft" data-wow-duration="1s" data-wow-delay=".1s">
                                <a href="{% url 'accounts:signup' %}" class="boxed-btn3">Get Start Now</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-5 col-md-6">
                        <div class="phone_thumb wow fadeInDown home_main_image" data-wow-duration="1.1s" data-wow-delay=".2s">
                            <img src="{% static 'home/img/home/first_seen_main_img.png' %}"  alt="subforsub get more subscribers">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider_area_end -->
    <!-- service_area  -->
    <div class="service_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4">
                    <div class="single_service text-center wow fadeInUp" data-wow-duration=".6s" data-wow-delay=".4s">
                        <div class="thumb">
                            <img src="{% static 'home/img/icon/2.svg' %}" alt="subforsub get more subscribers">
                        </div>
                        <h3>Get Subscribers by<br> using SubForSub</h3>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="single_service text-center wow fadeInUp" data-wow-duration=".7s" data-wow-delay=".5s">
                        <div class="thumb">
                            <img src="{% static 'home/img/icon/1.svg' %}"  alt="subforsub get more subscribers">
                        </div>
                        <h3>Complete Surveys<br> to get subscribers</h3>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4">
                    <div class="single_service text-center wow fadeInUp " data-wow-duration=".8s" data-wow-delay=".6s">
                        <div class="thumb">
                            <img src="{% static 'home/img/icon/3.svg' %}"  alt="subforsub get more subscribers">
                        </div>
                        <h3>Instant Subscribers by some tasks</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ service_area  -->

    <!-- service_area_2  -->
    <div class="service_area_2">
        <div class="container">
            <div class="service_content_wrap">
                <div class="row">
                    <div class="col-lg-4 col-md-4">
                        <div class="single_service  wow fadeInUp" data-wow-duration=".5s" data-wow-delay=".3s">
                            <span>01</span>
                            <h3>Sign Up for free</h3>
                            <p>Not only the signup our whole service is full free. So the first step is to create Your account and continue</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4">
                        <div class="single_service  wow fadeInUp" data-wow-duration=".6s" data-wow-delay=".4s">
                            <span>02</span>
                            <h3>Sub4Sub OR Tasks OR Surveys</h3>
                            <p>Sub4Sub OR Tasks OR Surveys are the main methods to get subscribers. Every method has It's Pros and Cons So Watchout</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-4  wow fadeInUp" data-wow-duration=".7s" data-wow-delay=".5s">
                        <div class="single_service">
                            <span>03</span>
                            <h3>Enjoy Your channel growth</h3>
                            <p>Last step is to watch the channel grow. </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ service_area_2  -->

    <!-- footer start -->
    <footer class="footer">
        <div class="copy-right_text">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This platform is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by Techlio Company</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- JS here -->
    <script src="{% static 'home/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'home/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'home/js/popper.min.js' %}"></script>
    <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'home/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'home/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'home/js/ajax-form.js' %}"></script>
    <script src="{% static 'home/js/waypoints.min.js' %}"></script>
    <script src="{% static 'home/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'home/js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'home/js/scrollIt.js' %}"></script>
    <script src="{% static 'home/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'home/js/wow.min.js' %}"></script>
    <script src="{% static 'home/js/nice-select.min.js' %}"></script>
    <script src="{% static 'home/js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'home/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'home/js/plugins.js' %}"></script>
    <script src="{% static 'home/js/gijgo.min.js' %}"></script>

    <!--contact js-->
    <script src="{% static 'home/js/contact.js' %}"></script>
    <script src="{% static 'home/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'home/js/jquery.form.js' %}"></script>
    <script src="{% static 'home/js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'home/js/mail-script.js' %}"></script>

    <script src="{% static 'home/js/main.js' %}"></script>
</body>

</html>