accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('signup/', views.UserSignUpView.as_view(), name='signup'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.IndexAccountView.as_view(), name='index_account'),
    path('findOther/', views.FindOtherPeopleView.as_view(), name='find_other'),
    path('findOther/detail/<int:pk>/', views.FindOtherPeopleDetailView.as_view(), name='find_other_detail'),
    path('findOther/detail/<int:pk>/comment/', views.FindOtherPeopleDetailCommentView.as_view(), name='find_other_detail_comment'),

    path('findMoreSubscribers/', views.FindMoreSubscriberView.as_view(), name='find_more_subscribers'),
    
    path('subscribersSurvey/', views.SubscribersSurveyView.as_view(), name='subscribers_survey'),

    path('settings/', views.SettingsView.as_view(), name='settings'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
	path('', views.IndexView.as_view(), name='index')
]

sub4sub/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.returnToHome),

    path('home/', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('survey/', include('survey.urls')),
    path('dashboard/', include('dashboard.urls')),
]

dashboard/models.py
from django.db import models

class Comment(models.Model):
    owner_user_profile = models.ForeignKey('accounts.Signal_User_Profile', on_delete=models.CASCADE)
    comment_text = models.TextField(max_length=5000)

    def __str__(self):
        return str(self.comment_text[:50])

dashboard/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import generic

from accounts.models import Signal_User_Profile
from .models import Comment

class IndexAccountView(generic.TemplateView):
    template_name = 'dashboard/index_account.html'
# ===================================================================================
# Find Others
class FindOtherPeopleView(generic.TemplateView):
    template_name = 'dashboard/find_other.html'

    def get_context_data(self, **kwargs):
        context = super(FindOtherPeopleView, self).get_context_data(**kwargs)
        context['users_list'] = Signal_User_Profile.objects.all().order_by('-id')[:11]
        return context
# Find Others : Detail
class FindOtherPeopleDetailView(generic.View):
    template_name = 'dashboard/find_other_detail.html'

    def get(self, request, pk):
        current_signal_profile = Signal_User_Profile.objects.get(pk=pk)
        context = {'object':current_signal_profile}
        context['owned_comment_list'] = Signal_User_Profile.objects.get(pk=pk).owned_comments.all()
        return render(request, self.template_name, context)

# Find Others : Detail : Comment
class FindOtherPeopleDetailCommentView(generic.View):
    def post(self, request, pk):
        commentValue = request.POST['comment-value']
        # Creating the new Comment
        new_comment = Comment()
        new_comment.owner_user_profile = request.user.signal_user_profile
        new_comment.comment_text = commentValue
        new_comment.save()
        # Adding this comment to the related Signal User
        current_viewed_signal_user = Signal_User_Profile.objects.get(id=pk)
        current_viewed_signal_user.owned_comments.add(new_comment)
        current_viewed_signal_user.save()

        # Returning Success Http Response
        return HttpResponse('Success!')

# =======================================================================================
# Find More Subscribers by Other Methods
class FindMoreSubscriberView(generic.View):
    template_name = 'dashboard/find_more_subscribers.html'

    def get(self, request):
        if (request.user.signal_user_profile.is_on_survey == True):
            return redirect('dashboard:subscribers_survey')
        else:
            return render(request, self.template_name, {})

# =======================================================================================
# Survey
class SubscribersSurveyView(generic.View):
    def get(self, request):
        # Setting That User is on a Survey
        request.user.signal_user_profile.is_on_survey = True
        request.user.signal_user_profile.save()
        # Getting all channels by survey points
        context = {}
        # Subtracting One from Survey points of rendering subscribers list
        channels_to_subscribe = []
        for channel in Signal_User_Profile.objects.all().order_by('survey_points')[:5]:
            channel.survey_points -= 1
            channel.save()
            channels_to_subscribe.append(channel)

        context['channels_to_subscribe'] =  channels_to_subscribe

        return render(request, 'dashboard/surveys/subscribers_survey.html', context)

    def post(self, request):
        print('We are on post!')
        request.user.signal_user_profile.survey_points += 5
        request.user.signal_user_profile.is_on_survey = False
        request.user.signal_user_profile.save()
        return HttpResponse('success')

# =======================================================================================
# Settings
class SettingsView(generic.TemplateView):
    template_name = 'dashboard/settings.html'

dashboard/templates/dashboard/find_more_subscribers.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Find More Subscribers | SubForSub - The Best SubForSub System for You To Get More Subscribers</title>

    {% load static %}
    <!-- SEO METAS LISTOUT -->
    {% include 'seo_metas.html' %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'dashboard/materialize/css/materialize.min.css' %}" media="screen,projection" />
    <!-- Bootstrap Styles-->
    <link href="{% static 'dashboard/css/bootstrap.css' %}" rel="stylesheet" />
    <!-- FontAwesome Styles-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
    <!-- Morris Chart Styles-->
    <link href="{% static 'dashboard/js/morris/morris-0.4.3.min.css' %}" rel="stylesheet" />
    <!-- Custom Styles-->
    <link href="{% static 'dashboard/css/custom-styles.css' %}" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link rel="stylesheet" href="{% static 'dashboard/js/Lightweight-Chart/cssCharts.css' %}"> 
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default top-navbar" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand waves-effect waves-dark" href="index.html"><i class="large material-icons">track_changes</i> <strong>SubForSub</strong></a>
				
		        <div id="sideNav" href=""><i class="material-icons dp48">toc</i></div>
            </div>

            <ul class="nav navbar-top-links navbar-right"> 
				<!-- <li><a class="dropdown-button waves-effect waves-dark" href="#!" data-activates="dropdown4"><i class="fa fa-envelope fa-fw"></i> <i class="material-icons right">arrow_drop_down</i></a></li>				
				<li><a class="dropdown-button waves-effect waves-dark" href="#!" data-activates="dropdown3"><i class="fa fa-tasks fa-fw"></i> <i class="material-icons right">arrow_drop_down</i></a></li>
				<li><a class="dropdown-button waves-effect waves-dark" href="#!" data-activates="dropdown2"><i class="fa fa-bell fa-fw"></i> <i class="material-icons right">arrow_drop_down</i></a></li> -->
				  <li><a class="dropdown-button waves-effect waves-dark" href="#!" data-activates="dropdown1"><i class="fa fa-user fa-fw"></i> <b>{{ user.username }}</b> <i class="material-icons right">arrow_drop_down</i></a></li>
            </ul>
        </nav>
		<!-- Dropdown Structure -->
        <ul id="dropdown1" class="dropdown-content">
            <li><a href="#"><i class="fa fa-user fa-fw"></i> My Profile</a></li>
            <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a></li> 
            <li><a href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
        </ul>
        <ul id="dropdown2" class="dropdown-content w250">
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-comment fa-fw"></i> New Comment
                        <span class="pull-right text-muted small">4 min</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-twitter fa-fw"></i> 3 New Followers
                        <span class="pull-right text-muted small">12 min</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-envelope fa-fw"></i> Message Sent
                        <span class="pull-right text-muted small">4 min</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-tasks fa-fw"></i> New Task
                        <span class="pull-right text-muted small">4 min</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <i class="fa fa-upload fa-fw"></i> Server Rebooted
                        <span class="pull-right text-muted small">4 min</span>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a class="text-center" href="#">
                    <strong>See All Alerts</strong>
                    <i class="fa fa-angle-right"></i>
                </a>
            </li>
        </ul>
        <ul id="dropdown3" class="dropdown-content dropdown-tasks w250">
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Task 1</strong>
                            <span class="pull-right text-muted">60% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                <span class="sr-only">60% Complete (success)</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Task 2</strong>
                            <span class="pull-right text-muted">28% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="28" aria-valuemin="0" aria-valuemax="100" style="width: 28%">
                                <span class="sr-only">28% Complete</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Task 3</strong>
                            <span class="pull-right text-muted">60% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                <span class="sr-only">60% Complete (warning)</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <div>
                        <p>
                            <strong>Task 4</strong>
                            <span class="pull-right text-muted">85% Complete</span>
                        </p>
                        <div class="progress progress-striped active">
                            <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 85%">
                                <span class="sr-only">85% Complete (danger)</span>
                            </div>
                        </div>
                    </div>
                </a>
            </li>
            <li class="divider"></li>
            <li>
        </ul>   
        <ul id="dropdown4" class="dropdown-content dropdown-tasks w250 taskList">
            <li>
                <div>
                    <strong>{{ user.username }}</strong>
                    <span class="pull-right text-muted">
                        <em>Today</em>
                    </span>
                </div>
                <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...</p>
                </a>
            </li>
                <li class="divider"></li>
                <li>
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <p>Lorem Ipsum has been the industry's standard dummy text ever since an kwilnw...</p>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="#">
                        <div>
                            <strong>John Smith</strong>
                            <span class="pull-right text-muted">
                                <em>Yesterday</em>
                            </span>
                        </div>
                        <p>Lorem Ipsum has been the industry's standard dummy text ever since the...</p>
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text-center" href="#">
                        <strong>Read All Messages</strong>
                        <i class="fa fa-angle-right"></i>
                    </a>
                </li>
            </ul>  
	        <!--/. NAV TOP  -->
            <!--/. NAV TOP  -->
            <nav class="navbar-default navbar-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav" id="main-menu">
                        <li>
                            <a href="{% url 'dashboard:find_more_subscribers' %}" class="active-menu waves-effect waves-dark"><i class="fab fa-youtube"></i> Get More Subscribers</a>
                        </li>
                        <li>
                            <a href="{% url 'dashboard:find_other' %}" class="waves-effect waves-dark"><i class="fa fa-users"></i> Find Others For SubForSub</a>
                        </li>
                        <li>
                            <a href="{% url 'dashboard:index_account' %}" class="waves-effect waves-dark"><i class="fa fa-qrcode"></i> My Account</a>
                        </li>
                        <li>
                            <a href="{% url 'dashboard:settings' %}" class="waves-effect waves-dark"><i class="fa fa-qrcode"></i> Settings</a>
                        </li>
                    </ul>
                </div>

            </nav>
            <!-- /. NAV SIDE  -->
            <div id="page-wrapper" >
			    <div class="header"> 
                    <h1 class="page-header">Get More Subscribers</h1>
					<ol class="breadcrumb">
					    <li><a href="#">Home</a></li>
					    <li class="active">Get More Subscribers</li>
					</ol> 					
		        </div>
		
                <div id="page-inner"> 
                                 
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div class="card survey-item">
                            <h3>Subscribers Survey</h3>
                            <a href="{% url 'dashboard:subscribers_survey' %}">Start</a>
                        </div>
                        <div class="card survey-item">
                            <h3>SubForSub Find Others</h3>
                            <a href="{% url 'dashboard:find_other' %}">Find Others</a>
                        </div>
                </div> 
                <!-- /. ROW  --> 
				<footer><p>All right reserved. Proudly Made By Techlio</p></footer>
			</div>
			 <!-- /. PAGE INNER  -->
        </div>
        <!-- /. PAGE WRAPPER  -->
    </div>
    <!-- /. WRAPPER  -->
    <!-- JS Scripts-->
    <!-- jQuery Js -->
    <script src="{% static 'dashboard/js/jquery-1.10.2.js' %}"></script>
	
	<!-- Bootstrap Js -->
    <script src="{% static 'dashboard/js/bootstrap.min.js' %}"></script>
	
	<script src="{% static 'dashboard/materialize/js/materialize.min.js' %}"></script>
	
    <!-- Metis Menu Js -->
    <script src="{% static 'dashboard/js/jquery.metisMenu.js' %}"></script>
    <!-- Morris Chart Js -->
    <script src="{% static 'dashboard/js/morris/raphael-2.1.0.min.js' %}"></script>
    <script src="{% static 'dashboard/js/morris/morris.js' %}"></script>
	
	
	<script src="{% static 'dashboard/js/easypiechart.js' %}"></script>
	<script src="{% static 'dashboard/js/easypiechart-data.js' %}"></script>
	
	 <script src="{% static 'dashboard/js/Lightweight-Chart/jquery.chart.js' %}"></script>
	
    <!-- Custom Js -->
    <script src="{% static 'dashboard/js/custom-scripts.js' %}"></script> 
	<script>
	$(document).ready(function(){
	 $('ul.tabs').tabs();
		$('.collapsible').collapsible({
		  accordion: false, // A setting that changes the collapsible behavior to expandable instead of the default accordion style
		  onOpen: function(el) { alert('Open'); }, // Callback for Collapsible open
		  onClose: function(el) { alert('Closed'); } // Callback for Collapsible close
		}
	  );
	});
	</script>
 

</body>

</html>